php:
  build: .
  ports:
  - "80:80"
  volumes:
  - /home/suporte/docker/www/:/var/www/html
  links:
  - db
myadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports:
    - "8080:80"
  environment:
  - PMA_ARBITRARY=1
  - PMA_HOST=127.0.0.1
  restart: always
  links:
  - db
db:
  image: mysql:5.7
  ports:
   - "3306:3306"
  volumes:
  - /home/suporte/docker/mysql/:/var/lib/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=1234
  - MYSQL_DATABASE=suporte

